site_name: Winterbloom Sol User Guide
copyright: "© 2020 Winterbloom, licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/theacodes/Winterbloom-Sol"
edit_uri: edit/master/user_guide/docs
theme:
  name: cinder
extra_css:
  - "css/overrides.css"
markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: "#"
      toc_depth: 2
nav:
  - "User Guide": index.md